### ISSUE TITLE
Checkbox is not keyboard navigable

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#528] opened 2020-08-03 18:00 UTC
**Describe the bug**
The Checkbox component is not navigable with the keyboard.

**To Reproduce**
1. Go to 'https://cloud2.influxdata.com/splash'
2. Click on the company name field
3. Press tab to try to select the checkbox
4. See that checkbox is skipped in the tab order

**Expected behavior**
AS a user navigating with a keyboard only
WHEN I press the `tab` key to navigate to the Checkbox component in a form
THEN it should take the focus
WHEN I press `spacebar`
THEN the Checkbox should be toggled

**Screenshots**
![signup_tab_order](https://user-images.githubusercontent.com/11937365/89210604-409ad400-d575-11ea-85ff-18531b9f4dcf.gif)

**Comment by ShmuelLotman** [comment] 2021-02-01 00:09
Resolving. This seems to have been addressed somewhere, because testing this shows that this functionality exists and works as intended.

**Closed by ShmuelLotman** 2021-02-01 00:09 UTC
Labels: kind/bug
