### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Mshannon5** [influxdata/clockface#660] opened 2021-08-20 00:34 UTC
**Describe the bug**
 Currently when selecting an option in the TreeNav Menu it doesn’t automatically display the page you selected. As the Menu Bar remains open covering the whole screen you need to close it ('X' button) to view the selected page which isn't great for user experience..

**To Reproduce**
1. Go to TreeNav on mobile
2. Click on link to route to new page
3. New page loads in background of Navigation menu

**Expected behavior**
When navigating using the TreeNav on mobile, the menu should be collapsed after clicking on a link.
**Screenshots**
![image](https://user-images.githubusercontent.com/60203824/130160974-eb1f6b3a-a822-4aa2-a816-e70fc3afba73.png)

**Browser**
 - OS: Windows
 - Browser Chrome
 - Version 92

**Comment by daviddkkim** [comment] 2021-08-20 00:41
Hello @Mshannon5 ,
Thanks for pointing this out. 
I would say this isn't a 'Bug' or an 'error' since it is behaving as intended but it just happens to be a non-optimal experience. 
That's not to say I don't agree with you; this isn't an optimal experience as is.
To be transparent, Mobile view hasn't been a focus for us since very tiny fraction of our users ever view our application in mobile view. 
 
We have a new Navigation coming out in the next major version of clockface and will take this into consideration. Please keep an eye out for it! 

Thanks for using clockface :)

**Comment by TCL735** [comment] 2021-08-24 00:11
Closing this as it has been answered.

**Closed by TCL735** 2021-08-24 00:11 UTC
